### ISSUE TITLE
Turn editing on button not visible in courses with Sandstone swatch

### ISSUE THREAD

**Issue by trevormccready** [gjb2048/moodle-theme_foundation#11]
With version 3.9.1.6 installed with the Sandstone swatch, the TURN EDITING ON button is not visible. It appears that the SCSS file _header.scss sets the .pageheadingbutton .btn to a background-color and border-color transparent. This results in the button not being visible in courses. When we remove the _header.scss file the button is visible again.

**Comment by gjb2048** [comment]
@trevormccready Thanks for the report.  Interesting one, so I've added:

color: $body-color;

to the '.pageheadingbutton .btn' selector in _header.scss as the ethos of Foundation is to maintain its clean look.  Of course, how you modify your install is up to you.
