### ISSUE TITLE
$thiscoursemenu undefined error.

### ISSUE THREAD

**Issue by turf212** [gjb2048/moodle-theme_foundation#13]
Line 427 of classes/module/menus_module.php tries to return $output->render_the_menu($thiscoursemenu); in one of the if clauses but $thiscoursemenu is not defined until within a subsequent if clause.  When logged on as a user they are then prevented from accessing any courses.  Moving the return to within the correct if clause fixes the issue.

https://github.com/gjb2048/moodle-theme_foundation/blob/ff9df675c8b24c100c486b800e2dcc5ce3d27f94/classes/module/menus_module.php#L427

**Comment by gjb2048** [comment]
What version of Foundation are you running please?

**Comment by turf212** [comment]
Latest version available from the Moodle repositories.

**Comment by turf212** [comment]
Moodle 3.9 (if it wasn't clear from the title :) )

**Comment by gjb2048** [comment]
@turf212 Thanks for the spot, is a logic issue that I'll fix soon.
