### ISSUE TITLE
Slider display has changed with RC2

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#16]
Ok, gave up on my theme for a while and back to playing with yours!  I must say, I really do like this theme!  Not only because it is the only one out for 4.0!

Just upgraded to 4.0 RC2 and the slider display is not filling the screen and the text is no longer sitting on the slide.  See attached screenshot.

Also, feature request - do you think you would ever add the option to have a block area at the bottom of the front page like on the course pages?  And at the top on the course pages?  Sorry, do you want a separate issue for this...

<img width="1295" alt="Screen Shot 2022-04-14 at 1 54 41 PM" src="https://user-images.githubusercontent.com/2079129/163466040-eaaf3a4f-65c2-446f-901f-bfcf6c7d4f38.png">

**Comment by gjb2048** [comment]
@emmarichardson Thanks for praise and info with the slider, I'll investigate.

With the block regions, depends, but the code is a walk in the park for me, and Foundation is partly a vehicle for me to learn new skills / keep up to date, so tend in general to do the complex things that help me to keep ahead of the game.  I'm always open to having sponsored / paid for enhancements though.

**Comment by gjb2048** [comment]
@emmarichardson Working for me given the size of the images uploaded:
![Screenshot 2022-04-14 212747](https://user-images.githubusercontent.com/1058419/163470285-4290d7a4-faf8-4812-a336-7c01ecafc048.png)

**Comment by emmarichardson** [comment]
Oh, so it is meant to look like that - I thought before the image had automatically filled the space and the caption sat on top of the image.  My bad - must have confused it with a different theme maybe.  Sorry to waste your time then.

**Comment by gjb2048** [comment]
@emmarichardson No worries, I'd rather have a false report than miss a bug.

**Comment by gjb2048** [comment]
@emmarichardson P.s. In investigating, I played around with the theme a bit more and spotted issues with the notifications and messages menus = bug = this was a positive report.
