### ISSUE TITLE
On "Course Reuse" page dropdown missing

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#17]
On the Course Reuse interface, there is no a dropdown that lets you switch between different options (import/copy/backup/restore, etc).  It is missing in the Foundation theme.
On a similar note, there is similar dropdown menu on the participants page that is functional but does not look like a dropdown in Foundation.

**Comment by gjb2048** [comment]
@emmarichardson Thanks, please could you post screen shots so I know where exactly you mean.

**Comment by emmarichardson** [comment]
<img width="555" alt="Screen Shot 2022-04-19 at 1 14 18 PM" src="https://user-images.githubusercontent.com/2079129/164078704-77c3bc19-3bd6-48ad-ba19-45dbaef35d95.png">
<img width="814" alt="Screen Shot 2022-04-19 at 1 13 37 PM" src="https://user-images.githubusercontent.com/2079129/164078712-52df8030-a5bc-4581-ae22-86d94645fb39.png">
<img width="866" alt="Screen Shot 2022-04-19 at 1 13 28 PM" src="https://user-images.githubusercontent.com/2079129/164078714-acb7675a-9239-4acb-93df-e1717e3ce4ba.png">

**Comment by emmarichardson** [comment]
First screenshot is Boost, second one is Foundation, third screenshot is how you get to that screen...

**Comment by emmarichardson** [comment]
<img width="950" alt="Screen Shot 2022-04-19 at 1 16 37 PM" src="https://user-images.githubusercontent.com/2079129/164079120-cb1a5e09-8d38-457c-a991-f21d4e512d02.png">
<img width="952" alt="Screen Shot 2022-04-19 at 1 16 17 PM" src="https://user-images.githubusercontent.com/2079129/164079123-a908f49c-ab50-49c1-84c9-8ed98d4f70f5.png">

This is the dropdown on the Participants page - on the Foundation version (purple one), you can see that it just looks like a text box but it does still work if you click on it.  On this page it is just about aesthetics.

**Comment by gjb2048** [comment]
Ok, odd as both are 'tertiary-navigation' and yet work on participants and not on backup, odd.

**Comment by gjb2048** [comment]
Select not looking like select issue:

![Screenshot 2022-04-19 201944](https://user-images.githubusercontent.com/1058419/164079649-a65868bb-75a1-4787-9abc-c3b5eeb03582.png)

**Comment by emmarichardson** [comment]
Oh, and I did upgrade to the 4.0 stable release of moodle today and upgraded foundation to latest version in plugins database.

**Comment by gjb2048** [comment]
@emmarichardson Fixed both, thanks for reporting Emma, finding broken needles in a haystack takes ages!

**Comment by gjb2048** [comment]
@emmarichardson Now working for you? :)

**Comment by emmarichardson** [comment]
Yes, now working as expected - nice job...see, my real skill is finding bugs for all you amazing code writers!  Much easier than learning how to write the code myself...lol!

**Comment by gjb2048** [comment]
I've been writing software on and off since 1983, with the odd bit since 1979.
