### ISSUE TITLE
Completion status not showing on activity/return to course button

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#18]
When completing an activity, in Boost, there is a flag to show that whether activity has been completed or not - either says To Do or Done which is really a nice feature...it is not showing in Foundation.
A nice addition to any activity page would be a back to course button...because as I was trying out a choice question, I realized that you have to use the breadcrumb to get back to the course page which is not handy at all...I will most likely put this in tracker too..
<img width="589" alt="Screen Shot 2022-04-22 at 9 10 25 AM" src="https://user-images.githubusercontent.com/2079129/164743450-df63712a-48c7-45e0-9441-900f4c9a43bd.png">

**Comment by gjb2048** [comment]
@emmarichardson Interesting.  If you're running a test server and are happy to update via Git from https://github.com/gjb2048/moodle-theme_foundation (i.e. Git for Administrators in the Moodle docs), then I've added back activity navigation which has the dropdown to get back to the course page.

**Comment by emmarichardson** [comment]
Ok, see the dropdown but still no back to course..just a link to the next activity...
<img width="1261" alt="Screen Shot 2022-04-22 at 9 45 39 AM" src="https://user-images.githubusercontent.com/2079129/164749263-cd6830bd-08f8-4937-8311-c839ada3c38e.png">
.

**Comment by gjb2048** [comment]
Oh, drat, drat and double drat, was thinking of single page section navigation!

**Comment by gjb2048** [comment]
@emmarichardson All done, please update.

**Comment by emmarichardson** [comment]
Excellent - looks great now.
