### ISSUE TITLE
Failing core PHPUnit test

### ISSUE THREAD

**Issue by dragos5436** [gjb2048/moodle-theme_foundation#19]
Hi,

There is one PHPUnit test for this plugin that is failing:

```
component_test::test_get_component_classes_in_namespace
Error: Class 'block_settings_renderer' not found

/var/www/html/theme/foundation/classes/output/block_settings_renderer.php:34
/var/www/html/lib/classes/component.php:136
/var/www/html/lib/classes/component.php:908
/var/www/html/lib/tests/component_test.php:515
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97
```
MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE
executed with moodlehq/moodle-docker

**Comment by gjb2048** [comment]
@dragos5436 How can I replicate please as the tests within the theme do pass?  And what version of Moodle?

**Comment by gjb2048** [comment]
Ok, ran 'vendor\bin\phpunit lib/tests/component_test.php' on M4.0 and can replicate, test fails but code does work!
