### ISSUE TITLE
Controls for drawer-left-width and drawer-right-width

### ISSUE THREAD

**Issue by ecottis** [gjb2048/moodle-theme_foundation#21]
I was wondering if there is any way to change the drawer-left-width and drawer-right  width to make slightly more room in the main content section. my apologies if I have missed the setting.  (The Big Blue recording listing for example is too wide to fit in and overflows into the right hand block area.)

If  possible could you add a  control could to resize the left and right drawers.

Thanking you for your help

**Comment by gjb2048** [comment]
@ecottis No there isn't bar changing the code.  Yes its possible and a good idea.  I'll probably implement at some point.  If you need it sooner then I'd like to be paid for doing so please.

**Comment by ecottis** [comment]
I think I've worked out how to code in via Custom SCSS

.drawer-open {
    margin-left: **200px**;
}
[data-region="blocks-drawer"] {
    height: calc(100% - 50px);
    left: 0;
    overflow-y: auto;
    position: fixed;
    top: 50px;
    transition: all 0.75s;
    width: **200px;**
}
[data-region="blocks-column"] {
    width: **200px;**
    float: right;
}
#region-main.has-blocks {
    display: inline-block;
    width: calc(100% - **200px**);
}

Thanks a really good theme

**Comment by gjb2048** [comment]
@ecottis Fair enough, but in the Custom SCSS you only need the changed CSS attributes.
