### ISSUE TITLE
Collapsable in question preview won't work

### ISSUE THREAD

**Issue by miotto** [gjb2048/moodle-theme_foundation#22]
In the question bank, click on edit for a question and select preview. 
Expanding Preview options, Display options and Comments does not work.

Test with Moodle 4.0.1+ (Build: 20220519) and foundation Version 4.0.1.1 (2022041701)

**Comment by gjb2048** [comment]
@miotto Thanks for the report, fixed in https://github.com/gjb2048/moodle-theme_foundation/commit/9f95a964cfc151006f48b4c2976ab9fbc95bbfb7.

**Comment by ecottis** [comment]
Thanks Gareth


Kind Regards
Eddie

**Comment by gjb2048** [comment]
@miotto I've edited your comment to remove your personal information that will be public here on GitHub.
