### ISSUE TITLE
Activity description not showing

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#24]
I just realized that the activity description does not display - I have attached screenshots from boost and foundation..
<img width="1028" alt="Screen Shot 2022-06-08 at 3 14 53 PM" src="https://user-images.githubusercontent.com/2079129/172718962-fb32afc2-7d96-4589-b09e-d70a07359672.png">
<img width="1341" alt="Screen Shot 2022-06-08 at 3 15 08 PM" src="https://user-images.githubusercontent.com/2079129/172718970-ba6c01f1-59a5-45f1-9308-84f594de045f.png">

**Comment by emmarichardson** [comment]
In fact it seems to be missing the entire header...I have been through my additional css and do not see anything that would affect that.

**Comment by gjb2048** [comment]
Cannot replicate:
![Screenshot 2022-06-08 at 22-28-20 GD_1 A test](https://user-images.githubusercontent.com/1058419/172720666-d1f1bf71-76b5-44e6-9f90-cc430e5c36bc.png)
![Screenshot 2022-06-08 at 22-28-34 GD_1 A test](https://user-images.githubusercontent.com/1058419/172720669-76f30a52-6a3b-4ab5-be3e-300a92a97f01.png)

**Comment by emmarichardson** [comment]
Sorry, upgraded to latest version and it is showing now.  I either jacked up something in your code or it was something that already was fixed.  Didn't realize I was using old code.

**Comment by gjb2048** [comment]
And with the same activity completion:
![Screenshot 2022-06-08 at 22-30-48 GD_1 A test](https://user-images.githubusercontent.com/1058419/172720991-bcac5fed-0ee0-49c4-a2fb-236feda4bef7.png)
![Screenshot 2022-06-08 at 22-30-59 GD_1 A test](https://user-images.githubusercontent.com/1058419/172720992-35f41245-dc89-44fd-833d-efca9daa6b29.png)
