### ISSUE TITLE
Editing Button clashes with Chat icon in Safari

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#26]
When using Safari browser, the editing on button is not functional.  I discovered that the graphic for the button for some reason sits on top of the chat icon and if you click to the right of the editing button in a blank space on the navbar, it will in fact function.  The chat icon is not accessible at all from Safari.  I have attached screenshots of the view from Safari and the view from Chrome.
I have tested this on both my live and dev sites.  I also went through my additional css and removed each piece individually to verify that it was not interfering with the view.
<img width="272" alt="Screen Shot 2022-09-19 at 9 37 21 AM" src="https://user-images.githubusercontent.com/2079129/191056718-33a9ee63-4950-4084-9522-275d5b158a40.png">
<img width="280" alt="Screen Shot 2022-09-19 at 9 37 11 AM" src="https://user-images.githubusercontent.com/2079129/191056721-88c16121-4d62-45d2-b54a-26eecc083584.png">

**Comment by gjb2048** [comment]
Dear @emmarichardson I can't afford a Mac (electronic kind) or the cost of online testing tools on different platforms, so with the browser development tools in Safari, does removing the 'd-flex' markup on the form:

![Screenshot 2022-09-20 155321](https://user-images.githubusercontent.com/1058419/191292450-a7767843-cfd2-4d1d-9a51-4b376e9aad84.png)

solve the issue?

G

**Comment by emmarichardson** [comment]
That didn't help - I was able to get the icon to move to the right by removing an absolute position tag but it would still was not functioning correctly.  I will keep playing with it and see if I can figure it out.

**Comment by gjb2048** [comment]
@emmarichardson Thanks for trying.  The whole area is Flexbox orientated if that helps.

**Comment by gjb2048** [comment]
@emmarichardson Looked and core CSS is using some sort of padding adjustment to move things around, so please try the following custom CSS:

```
.navbar-nav .nav-editswitch .custom-switch {
  padding-left: 0;
  width: 1.75rem;
}

.navbar-nav .nav-editswitch .custom-switch .custom-control-label::before {
  left: 0;
}

.navbar-nav .nav-editswitch .custom-switch .custom-control-label::after {
  left: 2px;
}
```

and see if that fixes it please.

**Comment by emmarichardson** [comment]
That fixed it and does not interfere with Chrome display.  Thanks Gareth!

**Comment by gjb2048** [comment]
@emmarichardson Cool, I'll make it permanent.  Odd that Boost is not affected.

**Comment by emmarichardson** [comment]
Yes, a little weird but it is all the way to the right of the navbar in Boost so maybe that is why.

**Comment by gjb2048** [comment]
@emmarichardson This is the patch https://github.com/gjb2048/moodle-theme_foundation/commit/44558e151924747f9cf3bc611da605a4ecc2b9ac

**Comment by gjb2048** [comment]
Ah, forgot to remove the nbsp!

**Comment by gjb2048** [comment]
@emmarichardson Still an issue?

**Comment by emmarichardson** [comment]
No, I haven't noticed it and know that I have upgraded a time or two so you must have got it fixed.  Thanks Gareth!
