### ISSUE TITLE
Missing collapsible icons

### ISSUE THREAD

**Issue by miotto** [gjb2048/moodle-theme_foundation#27]
In Moodle 4.2 and Foundation Theme (master branch), I miss the collapsible icons in the blocks, e.g. navigation. In Moodle 4.1 and Foundation Theme (Version [V401.1.0]) it works. 
On the screenshot on the left is Moodle 4.1 and on the right is Moodle 4.2.
![collapse_block](https://user-images.githubusercontent.com/1874387/235142775-431293e6-d3c0-46f6-98e7-c3d56f0eadbf.png)
Is it a plugin or a Moodle problem?

Cheers

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-theme_foundation/commit/9274e92bfa499a7356db83154a4a48c8f775bef5
