### ISSUE TITLE
The course bulk editing does not work properly (Moodle 4.2)

### ISSUE THREAD

**Issue by miotto** [gjb2048/moodle-theme_foundation#28]
In Moodle 4.2 and Foundation Theme (master branch) the course bulk editing does not work properly.
It only works after I have copied the file 
`moodle/theme/boost/templates/core/sticky_footer.mustache` to 
`moodle/theme/foundation/templates/core/`

(Only the transparency of the sticky footer still seems a bit too much.)

Or is there a better way to import/activate the `sticky_footer.mustache` template for the Foundation Theme?

Thanks and Cheers

**Comment by gjb2048** [comment]
@miotto Sticky footer for the course?  The only thing I can find is for the mod_data module.

**Comment by gjb2048** [comment]
Ok, found the 'Bulk edit' at the top.

**Comment by gjb2048** [comment]
@miotto Please test https://github.com/gjb2048/moodle-theme_foundation/commit/76fffb1388adebfe9cd974f1238c19e48d59a7a6.

**Comment by miotto** [comment]
Ok I tested it and it works very well.
Thanks
