### ISSUE TITLE
Image Icon and Video Icon: Browse Repository button does not get any action to proceed to next screen. 

### ISSUE THREAD

**Issue by ngberger2015** [gjb2048/moodle-theme_foundation#29]
**Describe the bug**
After upgrading to 4.3 and using the 4.3 version of Foundation, trying to upload and insert an image no longer works. The pop-up shows the browse repository button but this has no action and display does not move on to the next screen 

**To Reproduce**
1. Go to editor (Tiny or Atto)
2. Click on 'image icon' to insert image
3. On Image properties, click on Browse Repository
4. No reaction

**Expected behavior**
Clicking Browse Repository should proceed to offer selection of file.

**Screenshots**

**Versions (please complete the following information):**
 - Moodle: 4.3
 - Theme: Foundation
 - Browser and version [Chrome latest, Firefox latest, Edge latest]

**JSON settings export**
This can help with replication, but be aware that the values could contain information that is specific to your site.  Therefore please 'ensure' that you check the text throughly before adding, especially as these issues are public and can be read by anybody!

1. As a site administrator, go to 'Site administration' -> 'Appearance' -> 'Themes' -> 'Foundation' -> 'Import / export settings'.
2. Navigate to the bottom of the page and click on 'Export properties as a JSON string'.
3. Select and copy everything between the curly brackets '{' and '}'.
4. Paste into a text editor and check the contents for anything that you don't want to be public.  If there is something, then remove it leaving an empty pair of double quotes '""'.
5. Copy and paste into the issue.

{"moodle_version":"2023100900","theme_version":"2023100700","alertpage1":"all","alerttext1":"\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003E.\u003Cbr\u003E\u003C\/p\u003E","alerttitle1":"Maintenance","alerttype1":"info","blocksperrow":"2","courseendblocksperrow":"3","customscss":"","displayhiddenmycourses":"1","displaymycourses":"1","displaythiscourse":"1","enablealert1":"","faiv":"","fav":"0","favicon":"\/NGBicon~1.ico","footerantigravityhorizontaloffset":"0","footerantigravityverticaloffset":"0","frontpagecarouselslides":"8","frontpageenableslide1":"1","frontpageenableslide2":"1","frontpageenableslide3":"1","frontpageenableslide4":"1","frontpageenableslide5":"1","frontpageenableslide6":"1","frontpageenableslide7":"1","frontpageenableslide8":"1","frontpageslidecaption1":"\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003E\u003C\/p\u003E\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003E5.8.2023\u003C\/p\u003E","frontpageslidecaption2":"\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003E\u003C\/p\u003E\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003E\u003C\/p\u003E\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003E\u003Cbr\u003E\u003C\/p\u003E","frontpageslidecaption3":"\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003E. \u003Ca href=\u0022https:\/\/moodle.ngberger.com\/course\/view.php?id=575\u0022\u003E\u003C\/a\u003E.\u003C\/p\u003E","frontpageslidecaption4":"\u003Cp dir=\u0022ltr\u0022 style=\u0022text-align: left;\u0022\u003EThis online course starts on March 7th, 2023 in the afternoon. \u003Ca href=\u0022https: ...\394458","headerbackgroundbottomopacity":"0.9","headerbackgroundcourseimage":"no","headerbackgroundposition":"center","headerbackgroundstyle":"cover","headerbackgroundtopcolour":"#3862ac","headerbackgroundtopopacity":"0.1","headerlangmenu":"course,frontpage,mydashboard,login","hvpcustomcss":"","hvpfontcss":" @font-face {\r\n font-family: \u0027Cabin Sketch\u0027;\r\n font-style: normal;\r\n font-weight: normal;\r\n src: url(\u0027[[font:theme|CabinSketch-Regular.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Cabin Sketch\u0027;\r\n font-style: normal;\r\n font-weight: bold;\r\n src: url(\u0027[[font:theme|CabinSketch-Bold.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Lato\u0027;\r\n font-style: normal;\r\n font-weight: 300;\r\n src: url(\u0027[[font:theme|Lato-Light.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Lato\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|Lato-Regular.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Lato\u0027;\r\n font-weight: 400;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|Lato-Italic.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Lato\u0027;\r\n font-style: normal;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|Lato-Bold.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 100;\r\n src: url(\u0027[[font:theme|Montserrat-Thin.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 100;\r\n src: url(\u0027[[font:theme|Montserrat-ThinItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 200;\r\n src: url(\u0027[[font:theme|Montserrat-ExtraLight.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 200;\r\n src: url(\u0027[[font:theme|Montserrat-ExtraLightItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 300;\r\n src: url(\u0027[[font:theme|Montserrat-Light.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 300;\r\n src: url(\u0027[[font:theme|Montserrat-LightItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|Montserrat-Regular.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|Montserrat-Italic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 500;\r\n src: url(\u0027[[font:theme|Montserrat-Medium.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 500;\r\n src: url(\u0027[[font:theme|Montserrat-MediumItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 600;\r\n src: url(\u0027[[font:theme|Montserrat-SemiBold.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 600;\r\n src: url(\u0027[[font:theme|Montserrat-SemiBoldItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|Montserrat-Bold.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|Montserrat-BoldItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 800;\r\n src: url(\u0027[[font:theme|Montserrat-ExtraBold.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 800;\r\n src: url(\u0027[[font:theme|Montserrat-ExtraBoldItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: normal;\r\n font-weight: 900;\r\n src: url(\u0027[[font:theme|Montserrat-Black.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Montserrat\u0027;\r\n font-style: italic;\r\n font-weight: 900;\r\n src: url(\u0027[[font:theme|Montserrat-BlackItalic.otf]]\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027News Cycle\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|NewsCycle-Regular.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027News Cycle\u0027;\r\n font-style: normal;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|NewsCycle-Bold.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Nunito Sans\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|NunitoSans-Regular.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Nunito Sans\u0027;\r\n font-style: normal;\r\n font-weight: 600;\r\n src: url(\u0027[[font:theme|NunitoSans-SemiBold.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Open Sans\u0027;\r\n font-style: normal;\r\n font-weight: 300;\r\n src: url(\u0027[[font:theme|OpenSans-Light-webfont.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Open Sans\u0027;\r\n font-weight: 300;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|OpenSans-LightItalic-webfont.ttf]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Open Sans\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|OpenSans-Regular-webfont.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Open Sans\u0027;\r\n font-weight: 400;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|OpenSans-Italic-webfont.ttf]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Open Sans\u0027;\r\n font-style: normal;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|OpenSans-Bold-webfont.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Open Sans\u0027;\r\n font-weight: 700;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|OpenSans-BoldItalic-webfont.ttf]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Raleway\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|Raleway-Regular.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Raleway\u0027;\r\n font-style: normal;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|Raleway-Bold.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Roboto\u0027;\r\n font-style: normal;\r\n font-weight: 300;\r\n src: url(\u0027[[font:theme|Roboto-Light-webfont.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Roboto\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|Roboto-Regular-webfont.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Roboto\u0027;\r\n font-style: normal;\r\n font-weight: 500;\r\n src: url(\u0027[[font:theme|Roboto-Medium-webfont.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Roboto\u0027;\r\n font-style: normal;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|Roboto-Black-webfont.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 200;\r\n font-style: normal;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-ExtraLight.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 200;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-ExtraLightIt.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 300;\r\n font-style: normal;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-Light.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 300;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-LightIt.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 400;\r\n font-style: normal;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-Regular.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 400;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-It.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 600;\r\n font-style: normal;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-Semibold.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 600;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-SemiboldIt.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 700;\r\n font-style: normal;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-Bold.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 700;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-BoldIt.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 900;\r\n font-style: normal;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-Black.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Source Sans Pro\u0027;\r\n font-weight: 900;\r\n font-style: italic;\r\n font-stretch: normal;\r\n src: url(\u0027[[font:theme|SourceSansPro-BlackIt.woff]]\u0027) format(\u0027woff\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Ubuntu\u0027;\r\n font-style: normal;\r\n font-weight: 400;\r\n src: url(\u0027[[font:theme|Ubuntu-R.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n\r\n @font-face {\r\n font-family: \u0027Ubuntu\u0027;\r\n font-style: normal;\r\n font-weight: 700;\r\n src: url(\u0027[[font:theme|Ubuntu-B.ttf]]\u0027) format(\u0027truetype\u0027);\r\n }\r\n ","loginbackground":"\/20150813_153447sm.jpg","loginbackgroundopacity":"0.8","loginbackgroundstyle":"cover","marketingblocksperrow":"2","mycoursesmax":"0","mycoursesorder":"1","mycoursesorderidorder":"1","mycoursetitle":"course","navbareditswitch":"1","navbarposition":"top","navbarstyle":"dark","numberofalerts":"1","numberofbrands":"0","prescss":"","swatch":"pulse","swatchcustomblockquotesmallcolorcolour":"","swatchcustombodybgcolour":"","swatchcustombodycolorcolour":"","swatchcustomcardbgcolour":"","swatchcustomcardcolorcolour":"","swatchcustomcolours":"1","swatchcustomcomponentactivebgcolour":"","swatchcustomcomponentactivecolorcolour":"","swatchcustomdangercolour":"","swatchcustomdarkcolour":"","swatchcustomfontsizebase":"","swatchcustomheadingscolorcolour":"","swatchcustominfocolour":"","swatchcustomlightcolour":"","swatchcustomlineheightbase":"","swatchcustomprimarycolour":"#3862ac","swatchcustomsecondarycolour":"#394458","swatchcustomsuccesscolour":"","swatchcustomtextmutedcolour":"","swatchcustomtypography":"","swatchcustomwarningcolour":"","syntaxhighlight":"1","syntaxhighlightversion":"3.0.83","trio":"","unaddableblocks":"","usermenulogouturl":""}
![Uploading Screenshot 2023-10-11 225816.png…]()

**Additional context**

**Comment by ngberger2015** [comment]
I have the same issue on 2 other servers, one public and one local. The upgrade went ahead without any problems but a day later when trying to edit, I discovered this error. Current workaround switch to other theme, but students currently online are not familiar with them and are not able to upload images. The same issue affects media files.

**Comment by gjb2048** [comment]
Dear @ngberger2015,

I believe that I have a solution with https://github.com/gjbarnard/moodle-theme_foundation/commit/83e6677cde5d8b6ca353f10074d9ecb13a007c31 - you should be able to patch the theme with the file as a direct replacement without issues.

G

**Comment by gjb2048** [comment]
@ngberger2015 Please see: https://moodle.org/mod/forum/discuss.php?d=451231#p1814281.
