### ISSUE TITLE
User menu on mobile

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_foundation#3]
![f_usermenu_mobile](https://user-images.githubusercontent.com/1058419/60193799-2fd74500-9830-11e9-80f0-299eb57864ca.PNG)

**Comment by gjb2048** [comment]
.navbar-nav .dropdown-menu {
    position: absolute;
    right: 0;
    left: auto;
}

**Comment by miotto** [comment]
The code affects the dropdown list of 'My courses'. 

![foundation_mycourses](https://user-images.githubusercontent.com/1874387/60500082-fe3ffd00-9cb9-11e9-9235-b9ee680c452e.png)

I think it should be called more specific for the user menu 
```
.navbar-nav .usermenu .dropdown-menu {
    left: auto;
    position: absolute;
    right: 0;
}
```

**Comment by gjb2048** [comment]
Ta.

**Comment by gjb2048** [comment]
Updated.
