### ISSUE TITLE
Site Logo needs Alt Text for Accessibility

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#30]
**Describe the bug**
When using Foundation, Accessiblity checker are throwing an error because the logo does not include Alt Text.  This issue does not happen when I switch to Boost.  

**To Reproduce**
1. Go to Home page.
2. Run any Accessibility Checker.
3. Check errors.
4. See that Site Logo is flagged for no Alt Text.

**Expected behavior**
This should include Alt Text.

**Versions (please complete the following information):**
 - Moodle: [4.1,4.2)
 - Theme: 4.0.1.3
 - All browsers - Chrome/Brave/Safari

**Comment by gjb2048** [comment]
Dear Emma,

Thanks for the report, I'll look as soon as I can.  M4.1 should be running a 4.1.x version of the theme please.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Can replicate.  Will fix as soon as I can.

**Comment by gjb2048** [comment]
Dear @emmarichardson,

All fixed and patched.  Will properly release on Moodle dot org at some point.

G

**Comment by emmarichardson** [comment]
Thanks, Gareth!

Emma Richardson
Distance Learning Coordinator
719-771-4022
Need to visit? Click below to schedule an appointment.
https://calendar.app.google/vy9C7FEp2GCNQrbE7

**Comment by gjb2048** [comment]
Dear Emma,

Released: https://moodle.org/mod/forum/discuss.php?d=456449.

G
