### ISSUE TITLE
4.3 Font Awesome Icon error when using theme version

### ISSUE THREAD

**Issue by emmarichardson** [gjb2048/moodle-theme_foundation#31]
**Describe the bug**
After upgrading to 4.3.3 and upgrading foundation to 403.1.2, when visiting front page of my site that has several font awesome icons on it, I received the following error:
Class constructor IconSystem cannot be invoked without 'new'

Switching to Core Font Awesome in the foundation settings fixed the error so it must be something missing in your theme version.

**Comment by gjb2048** [comment]
Dear @emmarichardson,

This has been fixed in https://github.com/gjbarnard/moodle-theme_foundation/commit/777030560f6eeb2184205e2e909cce7cb24fc775 - I've just not gotten around to releasing on Moodle dot org.

Gareth

**Comment by emmarichardson** [comment]
Thanks for letting me know.  Will have to pull down latest version.

**Comment by gjb2048** [comment]
Dear @emmarichardson,

Released: https://moodle.org/mod/forum/discuss.php?d=456449.

Kind regards,

Gareth
