### ISSUE TITLE
Assign grader

### ISSUE THREAD

**Issue by miotto** [gjb2048/moodle-theme_foundation#5]
The Foundation template `./mod/assign/templates/grading_navigation_user_selector.mustache` does not seem to work. The page is not filled. If I delete the template and the Moodle default template is used, it works.
![assign_grader_error](https://user-images.githubusercontent.com/1874387/60584039-71b23f00-9d8c-11e9-8194-d70c187b47a3.png)

**Comment by gjb2048** [comment]
M3.7+ only.
