### ISSUE TITLE
Error when adding questions to a quiz

### ISSUE THREAD

**Issue by miotto** [gjb2048/moodle-theme_foundation#6]
The commit e92d68f causes an error when adding questions to an empty quiz or with only a few questions.

![quiz_add_quest](https://user-images.githubusercontent.com/1874387/77234879-fb6f9a00-6bb1-11ea-8d71-8e3be84b0ecb.png)

Without this commit it looks right.

![quiz_add_q](https://user-images.githubusercontent.com/1874387/77235020-cdd72080-6bb2-11ea-9ed6-c573919391c8.png)

**Comment by gjb2048** [comment]
Ok, SCSS does not seem needed now, so removed.
