### ISSUE TITLE
No login with last version 3.9.1.0. No works

### ISSUE THREAD

**Issue by Luckasas** [gjb2048/moodle-theme_foundation#7]
With last version it shows the error: "Call to undefined function course_get_format()" if you login "https://www.myserver.com/moodle/login/index.php"

**Comment by gjb2048** [comment]
The theme does not call  course_get_format() - your Moodle is broken.

**Comment by Luckasas** [comment]
I'm sorry but I think that my server is ok.
I've installed a new Moodle in a new server and it happens again. A non modified Moodle with only your theme crashes when you "Log in".
I attach the video when you can see it.

[Gravació de pantalla 2020-10-08 a les 0.55.59.zip](https://github.com/gjb2048/moodle-theme_foundation/files/5344417/Gravacio.de.pantalla.2020-10-08.a.les.0.55.59.zip)

**Comment by gjb2048** [comment]
Duplicate of #8 - but reason is down to me.
